# Generated by Django 5.0.2 on 2024-04-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_client_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
