# Generated by Django 5.0.2 on 2024-05-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_client_address_alter_client_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
